### ISSUE TITLE
rat

### ISSUE THREAD

**Issue by abashir7866** [Galaxzy345/Deadcord#13]
https://minecraft-legit-cheat-free-no-rat-real-bypass.download/⁠‍​⁠‍​‍‌‍​‍‍‌‌​‌‌⁠‍‍‌‍‍⁠‍‍‍⁠​​​
look at this shit and prove that its not a rat

**Comment by Galaxzy345** [comment]
lmfao

**Comment by abashir7866** [comment]
My guy you tryna fuck with me? Is it a rat or no?

**Comment by Galaxzy345** [comment]
Use your brain, what does it look like? Hmm, there is a `__getToken` in the symbol tree. I wouldn't consider it a rat, more of a token grabber. Put two and two together.

**Comment by Galaxzy345** [comment]
That aint Deadcord, we dont do shit with your token.

**Comment by abashir7866** [comment]
What about the ChromePass OperaPass and FirefoxPass?

**Comment by abashir7866** [comment]
Why don't you share the source then?

**Comment by Galaxzy345** [comment]
Read the README. I dont know where the hell your getting those results from. Where did you download it? From GitHub? From another website?

**Comment by abashir7866** [comment]
I got it from the releases tab

**Comment by Galaxzy345** [comment]
Impossible, our users would have already found out, if we were to add a "virus" to Deadcord. What software are you using? Double Check.

**Comment by abashir7866** [comment]
Imma double check with my boy qoft. He did the debugging. I stg if he pulled a funni on me imma be pissed

**Comment by Galaxzy345** [comment]
Alright, let me know.

**Comment by Epik123** [comment]
> Alright, let me know.

galaxzy ur a fucking tard he trollin u

**Comment by FekSake** [comment]
> Imma double check with my boy qoft. He did the debugging. I stg if he pulled a funni on me imma be pissed

qoft? the dude that made vast.?

**Comment by Galaxzy345** [comment]
Hello Rise selfbot

**Comment by Galaxzy345** [comment]
Yall got a Discord I assume?

**Comment by FekSake** [comment]
> Hello Rise selfbot

tf?

**Comment by Galaxzy345** [comment]
Apparently they are here from their Discord.

**Comment by FekSake** [comment]
> https://minecraft-legit-cheat-free-no-rat-real-bypass.download/⁠‍​⁠‍​‍‌‍​‍‍‌‌​‌‌⁠‍‍‌‍‍⁠‍‍‍⁠​​​
> look at this shit and prove that its not a rat

you gotta be trolling. lol.

**Comment by Galaxzy345** [comment]
They are.
