### ISSUE TITLE
discord

### ISSUE THREAD

**Issue by MarioPizzano** [Galaxzy345/Deadcord#15]
can't join in discord i need the BetterDiscord plugin but it says invalid invite

**Comment by Galaxzy345** [comment]
It has been fixed, we have been having issues with invites recently.

**Comment by MarioPizzano** [comment]
> It has been fixed, we have been having issues with invites recently.

can i get the valid invite?

**Comment by Galaxzy345** [comment]
https://discord.gg/DsbrkKmMmC
