### ISSUE TITLE
Refuses to spam

### ISSUE THREAD

**Issue by 3jm** [Galaxzy345/Deadcord#16]
Constantly getting this error

[ INFO ] [ 17:35:15 ] Scraping user IDs and channel IDs. This may take a few moments.
[ ERROR ] [ 17:35:20 ] Could not start spam, make sure all bots have the same role and are in the target server.

even tho all the bots have the same roles and can talk in the channel.

**Comment by Galaxzy345** [comment]
I am aware of this issue, we are releasing a rewrite soon that fixes common problems, join our server for updates and news.
